apiVersion: batch/v1
kind: Job
metadata:
  name: vault-bootstrap-test-cluster
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: vault-bootstrap
      containers:
        - name: vault-cli
          image: alpine:3.19
          command:
            - /bin/sh
            - -c
            - |
              set -e

              apk add --no-cache curl bash jq

              # Install Vault CLI
              VAULT_VERSION="1.15.0"
              wget -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
              unzip vault_${VAULT_VERSION}_linux_amd64.zip
              mv vault /usr/local/bin/

              export VAULT_ADDR="http://vault.vault.svc.cluster.local:8200"
              export VAULT_TOKEN=$(cat /vault/admin-token)

              CLUSTER_NAME="${CLUSTER_NAME}"

              echo "Creating policy for ${CLUSTER_NAME}"

              cat <<EOF > /tmp/policy.hcl
              path "secret/metadata/${CLUSTER_NAME}/*" {
                capabilities = ["list", "read"]
              }
              path "secret/data/${CLUSTER_NAME}/*" {
                capabilities = ["read"]
              }
              EOF

              # Create or update policy (idempotent)
              vault policy write ${CLUSTER_NAME} /tmp/policy.hcl

              echo "Creating token for ${CLUSTER_NAME}"

              TOKEN=$(vault token create \
                -policy="${CLUSTER_NAME}" \
                -ttl="24h" \
                -format=json | jq -r '.auth.client_token')

              echo "Storing token in Kubernetes secret"

              kubectl create secret generic ${CLUSTER_NAME}-vault-token \
                --from-literal=token=${TOKEN} \
                --namespace=${CLUSTER_NAME} \
                --dry-run=client -o yaml | kubectl apply -f -

              echo "Bootstrap completed successfully"

          env:
            - name: CLUSTER_NAME
              value: "test-cluster"
          volumeMounts:
            - name: vault-admin
              mountPath: /vault
              readOnly: true
      volumes:
        - name: vault-admin
          secret:
            secretName: vault-admin-token
