apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: new-cluster
  description: "Postgres cluster"
  annotations:
    argocd/app-name: new-cluster
    vault.io/secrets-path: "secret/new-cluster"
    vault.io/secrets-engine: "secret"
    vault.io/kv-version: "2"
spec:
  type: database
  owner: guest
