apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: prod-cluster
  description: "Postgres cluster"
  annotations:
    argocd/app-name: prod-cluster
    vault.io/secrets-path: "prod-cluster"
spec:
  type: database
  owner: guest