apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cluster-test
  description: "Postgres cluster"
  annotations:
    argocd/app-name: cluster-test
    vault.io/secrets-path: "cluster-postgres-cluster-test/database"
    vault.io/secrets-engine: "secret"
    vault.io/kv-version: "2"

spec:
  type: database
  owner: guest
