apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  # This uses the cluster_name from your values
  name: {{ .Values.cluster_name }}
spec:
  # 1. Root/Admin Setup
  rootPasswordSecretKeyRef:
    # Variabilized name so it is unique to this cluster
    name: {{ .Values.cluster_name }}-root
    key: password
    generate: true

  # 2. Application Setup
  username: {{ .Values.db_user }}
  database: {{ .Values.db_name }}
  passwordSecretKeyRef:
    # Variabilized name for the app user secret
    name: {{ .Values.cluster_name }}-app-user
    key: password
    generate: true

  # Storage Configuration
  storage:
    size: {{ .Values.storage_size }}
    storageClassName: local-path

  port: 3306
  service:
    type: ClusterIP