apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  # This uses the cluster_name from your values
  name: my-mariadb
spec:
  # 1. Root/Admin Setup
  rootPasswordSecretKeyRef:
    # Variabilized name so it is unique to this cluster
    name: my-mariadb-root
    key: password
    generate: true

  # 2. Application Setup
  username: myuser
  database: mydb
  passwordSecretKeyRef:
    # Variabilized name for the app user secret
    name: my-mariadb-app-user
    key: password
    generate: true

  # Storage Configuration
  storage:
    size: 10
    storageClassName: standard

  port: 3306
  service:
    type: ClusterIP